#!/bin/sh

# launch sxhkd if not present
killall sxhkd
sxhkd &

# launch polybar
$HOME/.config/polybar/launch.sh

# bspwm settings
bspc monitor -d I II III IV V

bspc config border_width 0
bspc config window_gap 8
bspc config top_padding 34

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

# other settings
# feh --bg-fill [WALLPAPER_PATH]
xsetroot -cursor_name left_ptr
setxkbmap pl
picom --config $HOME/.config/picom/picom.conf &
